version: '3.5'
services:
  python-api:
    env_file: 
      - .env
    build: 
      context: frontend
    container_name: python-api
    image: teambd3/python-api:1.0.0
    ports:
    - 5000:5000
  dashboard:
    container_name: dashboard
    image: teambd3/dashboard:1.0.0
    build:
      context: dashboard
    volumes:
      - './dashboard:/app'
      - '/dashboard/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
 
